name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: slimluccii/scaleway-functions-deploy-action/.github/workflows/deploy.yml@main
    with:
      region: nl-ams
      scw_project_id: ae27d7c2-4a23-40f8-aa8b-15b28f6bb59f
      dist_path: dist
    secrets:
      scw_access_key_id: ${{ secrets.scw_access_key_id }}
      scw_secret_access_key: ${{ secrets.scw_secret_access_key }}

